# Follow config.yml
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 
# followDistance (default value is 7)
# The distance to follow someone, if not specified on the command line.
# Number of meters (blocks) expressed as a positive integer.
# Normal values will range from 5 to 15.
# Small numbers will cause you to follow very closely and will be harder to watch.
# Larger numbers will allow you to follow at a long distance and will be easier to watch.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 
# coolDown: (default value is 2)
# Time to wait between relocation teleport to prevent jumpy screen syndrome.
# Number of seconds expressed as a positive integer.
# Normal values will be between 1 and 5.
# Small numbers will cause lots of updates and will be harder to watch.
# Larger numbers will allow pauses between relocations and will be easier to watch.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 
# significantDistance (default value is 0.1999)
# The distance the followed player needs to move to trigger a relocation.
# Number of meters expressed as a floating point.
# Normal values will be between 0.10 and 0.22 (walking ~ 0.205 per update, YMMV).
# Small numbers will cause allow you to catch slow walk or sneaking.
# Larger numbers will allow you to ignore small changes, catch teleports and falling.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# 
# rotateHead (default value is false)
# Specifies whether you want to always move follower's head to face the followed player.
# This applies to the time within cool down period when followed player is still moving.
# True means always rotate the head, and may be a bit jumpy at close following distance.
# False means just stand still until the cool down period is expired.
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
followDistance: 7
coolDown: 2
significantDistance: 0.1999
rotateHead: false